spring.application.name=chat_be

# Database postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/chat
spring.datasource.username=postgres
spring.datasource.password=Huyhuy12
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


