spring.application.name=chat_be

# Load local .env (optional)
spring.config.import=optional:file:.env[.properties]

# Database postgresql
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#JWT
jwt.secret=${JWT_SECRET:w7nQcVsb+kX1hP+MFGF3AqlgJqXj9iD6KdqWlQWZyEk=}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION:36000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:259200000}

# B?t TRACE logging cho các thành ph?n STOMP và WebSocket c?t lõi c?a Spring
logging.level.org.springframework.messaging.simp.stomp=TRACE
logging.level.org.springframework.web.socket.handler=TRACE
logging.level.org.springframework.web.socket.server=TRACE
logging.level.org.springframework.messaging.simp.broker=TRACE
logging.level.org.springframework.messaging.simp.userregistry=TRACE

# B?n c?ng có th? mu?n gi? các log ? m?c DEBUG cho các thành ph?n messaging và websocket r?ng h?n
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.web.socket=DEBUG

# CORS / WebSocket
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:*}
app.ws.allowed-origins=${APP_WS_ALLOWED_ORIGINS:http://localhost:*}

# Auth cookie options
app.cookie.secure=${APP_COOKIE_SECURE:false}
app.cookie.same-site=${APP_COOKIE_SAME_SITE:Lax}
